    spring.application.name=salons-nearby
    server.port=8085
    spring.mongodb.uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:${MONGO_PORT}/salons?authSource=admin