spring.application.name=salons-nearby
server.port=8085
# local connection string
#spring.mongodb.uri=spring.mongodb.uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:${MONGO_PORT}/salons?authSource=admin

# docker container connection string
spring.mongodb.uri=${MONGODB_SERVICE_URI}
